namespace HextechRunes;

internal static class HextechPlayerRuneRegistry
{
	internal const string DefaultTagKey = "COMPREHENSIVE";

	internal static IReadOnlyList<PlayerRuneRegistration> Registrations => RuneRegistrations;

	private static readonly IReadOnlyList<PlayerRuneRegistration> RuneRegistrations =
    [
        Rune<SlapRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<DexterityToStrengthRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.AttributeConversionExclusive, tagKey: "OUTPUT"),
        Rune<StrengthToDexterityRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.AttributeConversionExclusive, tagKey: "SURVIVAL"),
        Rune<DexterityStrengthToFocusRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.AttributeConversionExclusive, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 1, tagKey: "ORB"),
        Rune<WizardlyThinkingRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 2, tagKey: "ORB"),
        Rune<NimbleRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<EscapePlanRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<BadTasteRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<FirstAidKitRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<RegenerationSuppressionRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, tagKey: "OUTPUT"),
        Rune<GiantSerpentsFangRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<AttackDefenseUnityRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<BlackCandleRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<SearingAttackRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<OverlordBloodArmorRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<BrokenGoldenCrownRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<BloodIdolRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<NonupeipeGenerosityRune>(HextechRarityTier.Silver, tagKey: "RANDOM"),
        Rune<BrightestFlameUpgradeRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<SpeedDemonRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<HeavyHitterRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<BigStrengthRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<TormentorRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<AdamantRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<MountainSoulRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<FrostWraithRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<BadgeBrothersRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<HomeguardRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<SwiftAndSafeRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<SacrificeRune>(HextechRarityTier.Silver, tagKey: "ECONOMY"),
        Rune<ProtectiveVeilRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<RepulsorRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<LightEmUpRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<UltimateUnstoppableRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<ThornmailRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<ZealotRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<MindToMatterRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<StatsRune>(HextechRarityTier.Silver, tagKey: "RANDOM"),
        Rune<StartupRoutineRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<CollectorRune>(HextechRarityTier.Silver, tagKey: "ECONOMY"),
        Rune<UnyieldingArmorRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<NightParadeRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<BloodPactRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 2, tagKey: "BLOODLETTING"),
        Rune<PlateletRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 3, tagKey: "BLOODLETTING"),
        Rune<SnakebiteRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 7, tagKey: "POISON"),
        Rune<CatalystRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 10, tagKey: "POISON"),
        Rune<SwordIntentRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 3, tagKey: "SWORDCRAFT"),
        Rune<FlawlessRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 4, tagKey: "COLORLESS"),
        Rune<CondensedRadianceRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 5, tagKey: "STARLIGHT"),
        Rune<RoyalCommandRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 10, tagKey: "SWORDCRAFT"),
        Rune<ByproductRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 7, tagKey: "STATUS"),
        Rune<ElectricSurgeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 9, tagKey: "ORB"),
        Rune<SoulCallingRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<TauntRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 5, tagKey: "DOOM"),
        Rune<SwordsmanshipRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 9, tagKey: "SWORDCRAFT"),
        Rune<AdvanceToRetreatRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 7, tagKey: "COMPREHENSIVE"),
        Rune<BoneGuardRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 12, tagKey: "SUMMON"),
        Rune<PlasterRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 13, tagKey: "SUMMON"),
        Rune<EasyDoesItRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<SweepingBladeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 14, tagKey: "OUTPUT"),
        Rune<BloodlettingUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 15, tagKey: "BLOODLETTING"),
        Rune<BattleTranceUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 16, tagKey: "RESOURCE"),
        Rune<JuggernautUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 18, tagKey: "OUTPUT"),
        Rune<DemonFormUpgradeRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 20, tagKey: "SURVIVAL"),
        Rune<ExposeUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 18, tagKey: "COMPREHENSIVE"),
        Rune<DecayRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 21, tagKey: "OUTPUT"),
        Rune<HiddenGemUpgradeRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<OceanDragonSoulRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<InfernalDragonSoulRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<HextechDragonSoulRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<CarefulSelectionRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<PowerShieldRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<CorrosionRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<DizzySpinningRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<WarmupExerciseRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<BerserkRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 11, tagKey: "RESOURCE"),
        Rune<BrutalityRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 12, tagKey: "BLOODLETTING"),
        Rune<CurtainCallRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 11, tagKey: "OUTPUT"),
        Rune<AllInRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 14, tagKey: "TRICK"),
        Rune<InstantDeathRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 18, tagKey: "DOOM"),
        Rune<DirgeUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 21, tagKey: "SUMMON"),
        Rune<ReanimateUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 22, tagKey: "SUMMON"),
        Rune<ReaperFormUpgradeRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 23, tagKey: "OUTPUT"),
        Rune<GloomyCloudsRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 14, tagKey: "ORB"),
        Rune<ZapUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 16, tagKey: "ORB"),
        Rune<AutomationUpgradeRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<DualcastUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 22, tagKey: "ORB"),
        Rune<RecycleBinRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 19, tagKey: "STATUS"),
        Rune<KnowThyPlaceUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 15, tagKey: "COMPREHENSIVE"),
        Rune<TyrannyUpgradeRune>(HextechRarityTier.Silver, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 18, tagKey: "VOID"),
        Rune<VoidFormUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 19, tagKey: "RESOURCE"),
        Rune<MentalShieldRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<PacifistRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<CrackTheEggRune>(HextechRarityTier.Silver, tagKey: "SURVIVAL"),
        Rune<KakaRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<BrutalForceRune>(HextechRarityTier.Silver, tagKey: "OUTPUT"),
        Rune<TransmuteGoldRune>(HextechRarityTier.Silver, tagKey: "RANDOM"),
        Rune<UniversalScopeRune>(HextechRarityTier.Silver, tagKey: "RESOURCE"),
        Rune<StokeRune>(HextechRarityTier.Silver, tagKey: "COMPREHENSIVE"),
        Rune<DullBladeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 22, tagKey: "BLOODLETTING"),
        Rune<BodySlamUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 23, tagKey: "OUTPUT"),
        Rune<ShriekUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 23, tagKey: "COMPREHENSIVE"),
        Rune<NowYouSeeMeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 27, tagKey: "STATUS"),
        Rune<DeadwoodRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 28, tagKey: "VOID"),
        Rune<BoneBreakUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 29, tagKey: "SUMMON"),
        Rune<UndyingUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 30, tagKey: "VOID"),
        Rune<SowUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 32, tagKey: "OUTPUT"),
        Rune<ReapUpgradeRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 33, tagKey: "OUTPUT"),
        Rune<ReprogramRune>(HextechRarityTier.Silver, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 24, tagKey: "COMPREHENSIVE"),

        Rune<JudicatorRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<TranscendentEvilRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 3, tagKey: "STACKING"),
        Rune<TankEngineRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "STACKING"),
        Rune<AstralBodyRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<AncientWineRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<PiggyBankRune>(HextechRarityTier.Gold, tagKey: "ECONOMY"),
        Rune<OrobasBlessingRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<CrossOrbRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<IllusoryWeaponRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<NeowsGrudgeRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "OUTPUT"),
        Rune<HolyFireRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<NoNonsenseRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<SuperBrainRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<OverflowRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<SturdyRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<LoopRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<OkBoomerangRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<DivineInterventionRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<SonataRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<ArchmageRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<NatureIsHealingRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<PorcupineRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<SnailFormRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<ColorDiscoveryRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<HattrickRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<AnthonyBiasRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<OmegaRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<ViolenceRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<CuttingEdgeAlchemistRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<DevilsDanceRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<BeginningAndEndRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 3, tagKey: "OUTPUT"),
        Rune<KeystoneHunterRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 1, tagKey: "TRICK"),
        Rune<WarmogsSpiritRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<RedEnvelopeRune>(HextechRarityTier.Gold, tagKey: "ECONOMY"),
        Rune<MindPurificationRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<EndlessRecoveryRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<SpeedsterRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<ServantMasterRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 1, tagKey: "SUMMON"),
        Rune<SoulEaterRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<DonationRune>(HextechRarityTier.Gold, tagKey: "ECONOMY"),
        Rune<TwiceThriceRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<BreadAndButterRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<BreadAndCheeseRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<BreadAndJamRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<FirebrandRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<NightstalkingRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<GetExcitedRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<ShrinkEngineRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "STACKING"),
        Rune<StatsOnStatsRune>(HextechRarityTier.Gold, tagKey: "RANDOM"),
        Rune<LifeFlowRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 1, tagKey: "EXHAUST"),
        Rune<RekindleRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 4, tagKey: "EXHAUST"),
        Rune<TrickLicenseRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 2, tagKey: "TRICK"),
        Rune<GalacticGiftRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 1, tagKey: "STARLIGHT"),
        Rune<SomethingFromNothingRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 2, tagKey: "VOID"),
        Rune<LubricantRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 4, tagKey: "COMPREHENSIVE"),
        Rune<HubrisRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "OUTPUT"),
        Rune<DrainRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 4, tagKey: "DOOM"),
        Rune<LethalTempoRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 3, tagKey: "SHIV"),
        Rune<EmergenceRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 5, tagKey: "ORB"),
        Rune<MirageRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 5, tagKey: "POISON"),
        Rune<AdaptiveCapacitorRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 8, tagKey: "ORB"),
        Rune<BarbarianWayRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 13, tagKey: "OUTPUT"),
        Rune<RenewalRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 4, tagKey: "TRICK"),
        Rune<WraithRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 6, tagKey: "OUTPUT"),
        Rune<SummonForthRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 2, tagKey: "SWORDCRAFT"),
        Rune<ImmortalBoneRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 7, tagKey: "SUMMON"),
        Rune<MakeItMineRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 8, tagKey: "STACKING"),
        Rune<DoomsdayRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 14, tagKey: "DOOM"),
        Rune<OldIdolRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<MonarchsGazeRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<HardBonesRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 11, tagKey: "SUMMON"),
        Rune<SendThemInRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 8, tagKey: "COMPREHENSIVE"),
        Rune<ChainInSleeveRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 9, tagKey: "SHIV"),
        Rune<RoyalTrialRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 11, tagKey: "SWORDCRAFT"),
        Rune<GoodLuckRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<RadianceRune>(HextechRarityTier.Gold, tagKey: "OUTPUT"),
        Rune<ManipulateRealityRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<BlueCandleMedkitRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<BigHandsRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 15, tagKey: "SUMMON"),
        Rune<JinlianBoxRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "RANDOM"),
        Rune<FleshAndBoneRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 16, tagKey: "SUMMON"),
        Rune<PortableSleepingBagRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<MoreTheMerrierRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<MirrorReflectionRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.FirstActExcluded, tagKey: "COMPREHENSIVE"),
        Rune<BloodArmorRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 9, tagKey: "BLOODLETTING"),
        Rune<ScaredStiffRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 10, tagKey: "EXHAUST"),
        Rune<DeviantCognitionRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 13, tagKey: "OUTPUT"),
        Rune<BashUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 21, tagKey: "OUTPUT"),
        Rune<IronWaveUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 25, tagKey: "OUTPUT"),
        Rune<CorpseExplosionRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 12, tagKey: "POISON"),
        Rune<SurvivorUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 16, tagKey: "SURVIVAL"),
        Rune<NeutralizeUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 20, tagKey: "OUTPUT"),
        Rune<SwordFlightRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 13, tagKey: "COMPREHENSIVE"),
        Rune<ElectrodynamicsRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 15, tagKey: "ORB"),
        Rune<MarkovBabbleRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 26, tagKey: "ORB"),
        Rune<CompactUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 17, tagKey: "STATUS"),
        Rune<HotfixUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 18, tagKey: "ORB"),
        Rune<VoltaicUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 20, tagKey: "ORB"),
        Rune<EchoFormUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 21, tagKey: "COMPREHENSIVE"),
        Rune<RainbowUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 23, tagKey: "ORB"),
        Rune<WhirlwindUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 17, tagKey: "OUTPUT"),
        Rune<StardustUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 16, tagKey: "STARLIGHT"),
        Rune<FallingStarUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 20, tagKey: "STARLIGHT"),
        Rune<BodyguardUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 19, tagKey: "SUMMON"),
        Rune<BorrowedTimeUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 20, tagKey: "RESOURCE"),
        Rune<UnleashUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 24, tagKey: "SUMMON"),
        Rune<MiseryUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 27, tagKey: "DOOM"),
        Rune<GoldCardCustomerRune>(HextechRarityTier.Gold, tagKey: "ECONOMY"),
        Rune<VampireCrawlerRune>(HextechRarityTier.Gold, tagKey: "COMPREHENSIVE"),
        Rune<EnlightenmentRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<WhiteHoleRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<TanksShieldRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<DawnbringersResolveRune>(HextechRarityTier.Gold, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<ShrinkRayRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<TransmutePrismaticRune>(HextechRarityTier.Gold, tagKey: "RANDOM"),
        Rune<MoreUniversalScopeRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<SnakebiteUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 24, tagKey: "POISON"),
#if !STS2_99_1 && !STS2_100_0
        Rune<InkshadowRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 25, tagKey: "SHIV"),
#endif
        Rune<SkyDrillUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 21, tagKey: "OUTPUT"),
        Rune<TrinityRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 22, tagKey: "STARLIGHT"),
        Rune<CrashLandingUpgradeRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 23, tagKey: "OUTPUT"),
        Rune<ChargeUpRune>(HextechRarityTier.Gold, tagKey: "RESOURCE"),
        Rune<AutoPatrolRune>(HextechRarityTier.Gold, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 31, tagKey: "SUMMON"),
        Rune<DeathHarvestRune>(HextechRarityTier.Gold, tagKey: "SURVIVAL"),
        Rune<HundredRefinementsRune>(HextechRarityTier.Gold, tagKey: "RANDOM"),

        Rune<EurekaRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<InfiniteLoopRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "STACKING"),
        Rune<SlowCookRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<GiantSlayerRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<CourageOfColossusRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<GlassCannonRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<FinalFormRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<BackToBasicsRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<DrawYourSwordRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.AttributeConversionExclusive, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 25, tagKey: "ORB"),
        Rune<FeelTheBurnRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<MikaelsBlessingRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<EarthAwakensRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "OUTPUT"),
        Rune<CorruptedBranchRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "EXHAUST"),
        Rune<SymphonyOfWarRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<UnmovableMountainRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<MysteryRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<MadScientistRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 27, tagKey: "ORB"),
        Rune<JeweledGauntletRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<HailToTheKingRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "COMPREHENSIVE"),
        Rune<DiceManiacRune>(HextechRarityTier.Prismatic, tagKey: "RANDOM"),
        Rune<ArcanePunchRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<PandorasBoxRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.FirstActExcluded, tagKey: "RANDOM"),
        Rune<TapDanceRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<InfernalConduitRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<DualWieldRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<GoliathRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<MasterOfDualityRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<HandOfBaronRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<CantTouchThisRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<QueenRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<UltimateRefreshRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<GoldrendRune>(HextechRarityTier.Prismatic, tagKey: "ECONOMY"),
        Rune<CerberusRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<CircleOfDeathRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<FanTheHammerRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<FeyMagicRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<WatchOutGrapefruitRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<ProteinShakeRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<StatsOnStatsOnStatsRune>(HextechRarityTier.Prismatic, tagKey: "RANDOM"),
        Rune<GoldenSpatulaRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.ThirdActExcluded, tagKey: "STACKING"),
        Rune<PrecisionCognitionRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 6, tagKey: "ORB"),
        Rune<HastyScribbleRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<ClownCollegeRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<BladeWaltzRune>(HextechRarityTier.Prismatic, tagKey: "OUTPUT"),
        Rune<SingularityAIRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<EightPennyGateRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<BreadSandwichRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.SelectionExcluded, tagKey: "COMPREHENSIVE"),
        Rune<MobileHomeRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<GrowingStrongerRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 5, tagKey: "OUTPUT"),
        Rune<GroundedRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 6, tagKey: "SURVIVAL"),
        Rune<FuriousGlareRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 24, tagKey: "OUTPUT"),
        Rune<KillerHunterRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 6, tagKey: "COMPREHENSIVE"),
        Rune<SerpentsFangRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 8, tagKey: "POISON"),
        Rune<ExplosionArtRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 6, tagKey: "SWORDCRAFT"),
        Rune<StarlightSplendorRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 7, tagKey: "STARLIGHT"),
        Rune<MiserableFateRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 9, tagKey: "DOOM"),
        Rune<DieForYouRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 10, tagKey: "SUMMON"),
        Rune<CompensationRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 25, tagKey: "DOOM"),
        Rune<OminousPactRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 26, tagKey: "DOOM"),
        Rune<HappyAccidentRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 10, tagKey: "STATUS"),
        Rune<MiseryRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<GhostFormRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<ForbiddenGrimoireRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<OneLaneBridgeRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<OrbSymbiosisRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 11, tagKey: "ORB"),
        Rune<NearDeathFeastRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 8, tagKey: "OUTPUT"),
        Rune<UnsealedThroneRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 12, tagKey: "RESOURCE"),
        Rune<CoreOverloadRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Defect, characterOrder: 12, tagKey: "ORB"),
        Rune<ForgottenSoulRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<UpgradeRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<OmniDragonSoulRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<ShoulderVakuRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<CardInspectionRune>(HextechRarityTier.Prismatic, tagKey: "DRAW"),
        Rune<PrimitiveMadnessRune>(HextechRarityTier.Prismatic, flags: PlayerRuneFlags.Disabled, tagKey: "COMPREHENSIVE"),
        Rune<ThoughtOverwriteRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Necrobinder, characterOrder: 17, tagKey: "VOID"),
        Rune<DoubleExistenceRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 13, tagKey: "RESOURCE"),
        Rune<TriPrismRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 14, tagKey: "COLORLESS"),
        Rune<QuantumComputingRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<MindOverMatterRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<DuffsVintageRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<NineDragonPowerRune>(HextechRarityTier.Prismatic, tagKey: "STACKING"),
        Rune<TezcatarasMercyRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<FlyingKickRune>(HextechRarityTier.Prismatic, tagKey: "SURVIVAL"),
        Rune<SellOffRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 15, tagKey: "TRICK"),
        Rune<GrandFinaleUpgradeRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 17, tagKey: "OUTPUT"),
        Rune<SerpentFormUpgradeRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 19, tagKey: "OUTPUT"),
        Rune<BigKnifeRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 22, tagKey: "SHIV"),
        Rune<VenerateUpgradeRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 17, tagKey: "STARLIGHT"),
        Rune<EchoRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 24, tagKey: "RESOURCE"),
        Rune<BlankCheckRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Regent, characterOrder: 25, tagKey: "COLORLESS"),
        Rune<SolidTimeRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
        Rune<ReforgedHelmetRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Ironclad, characterOrder: 19, tagKey: "OUTPUT"),
        Rune<MostUniversalScopeRune>(HextechRarityTier.Prismatic, tagKey: "RESOURCE"),
        Rune<TransmuteChaosRune>(HextechRarityTier.Prismatic, tagKey: "RANDOM"),
#if !STS2_99_1 && !STS2_100_0
        Rune<DoubleVisionRune>(HextechRarityTier.Prismatic, tagKey: "COMPREHENSIVE"),
#endif
        Rune<ExtremeSpeedRune>(HextechRarityTier.Prismatic, characterPool: PlayerRuneCharacterPool.Silent, characterOrder: 26, tagKey: "RESOURCE")
	];

	private static PlayerRuneRegistration Rune<TRune>(
		HextechRarityTier rarity,
		PlayerRuneFlags flags = PlayerRuneFlags.None,
		PlayerRuneCharacterPool? characterPool = null,
		int characterOrder = 0,
		string tagKey = DefaultTagKey)
	{
		return new PlayerRuneRegistration(typeof(TRune), rarity, flags, characterPool, characterOrder, tagKey);
	}
}
