namespace HextechRunes;

internal static class HextechMonsterHexRegistry
{
	internal static IReadOnlyList<MonsterHexRegistration> Registrations => MonsterHexRegistrations;

	private static readonly IReadOnlyList<MonsterHexRegistration> MonsterHexRegistrations =
	[
		Monster<SlapRune>(MonsterHexKind.Slap, HextechRarityTier.Silver),
		Monster<EscapePlanRune>(MonsterHexKind.EscapePlan, HextechRarityTier.Silver),
		Monster<HeavyHitterRune>(MonsterHexKind.HeavyHitter, HextechRarityTier.Silver),
		Monster<BigStrengthRune>(MonsterHexKind.BigStrength, HextechRarityTier.Silver),
		Monster<TormentorRune>(MonsterHexKind.Tormentor, HextechRarityTier.Silver, hasBurnHoverTip: true),
		Monster<ProtectiveVeilRune>(MonsterHexKind.ProtectiveVeil, HextechRarityTier.Silver),
		Monster<RepulsorRune>(MonsterHexKind.Repulsor, HextechRarityTier.Silver),
		Monster<ThornmailRune>(MonsterHexKind.Thornmail, HextechRarityTier.Silver),
		Monster<LightEmUpRune>(MonsterHexKind.LightEmUp, HextechRarityTier.Silver),
		Monster<MountainSoulRune>(MonsterHexKind.MountainSoul, HextechRarityTier.Silver),
		Monster<FirstAidKitRune>(MonsterHexKind.FirstAidKit, HextechRarityTier.Silver),
		Monster<SpeedDemonRune>(MonsterHexKind.SpeedDemon, HextechRarityTier.Silver),
		Monster<FrostWraithRune>(MonsterHexKind.FrostWraith, HextechRarityTier.Silver),
		Monster<BloodPactRune>(MonsterHexKind.BloodPact, HextechRarityTier.Silver),
		Monster<StartupRoutineRune>(MonsterHexKind.StartupRoutine, HextechRarityTier.Silver),
		Monster<DizzySpinningRune>(MonsterHexKind.DizzySpinning, HextechRarityTier.Silver),
		Monster<BrutalForceRune>(MonsterHexKind.BrutalForce, HextechRarityTier.Silver),
		Monster<ZealotRune>(MonsterHexKind.Zealot, HextechRarityTier.Silver),
		Monster<SwiftAndSafeRune>(MonsterHexKind.SwiftAndSafe, HextechRarityTier.Silver),
		Monster<BloodIdolRune>(MonsterHexKind.BloodIdol, HextechRarityTier.Silver),

		Monster<SturdyRune>(MonsterHexKind.Sturdy, HextechRarityTier.Gold),
		Monster<DawnbringersResolveRune>(MonsterHexKind.DawnbringersResolve, HextechRarityTier.Gold),
		Monster<ShrinkRayRune>(MonsterHexKind.ShrinkRay, HextechRarityTier.Gold),
		Monster<FirebrandRune>(MonsterHexKind.Firebrand, HextechRarityTier.Gold, hasBurnHoverTip: true),
		Monster<SuperBrainRune>(MonsterHexKind.SuperBrain, HextechRarityTier.Gold),
		Monster<NightstalkingRune>(MonsterHexKind.Nightstalking, HextechRarityTier.Gold),
		Monster<AstralBodyRune>(MonsterHexKind.AstralBody, HextechRarityTier.Gold),
		Monster<TankEngineRune>(MonsterHexKind.TankEngine, HextechRarityTier.Gold),
		Monster<ShrinkEngineRune>(MonsterHexKind.ShrinkEngine, HextechRarityTier.Gold),
		Monster<GetExcitedRune>(MonsterHexKind.GetExcited, HextechRarityTier.Gold),
		Monster<TwiceThriceRune>(MonsterHexKind.TwiceThrice, HextechRarityTier.Gold),
		Monster<LoopRune>(MonsterHexKind.Loop, HextechRarityTier.Gold),
		Monster<ServantMasterRune>(MonsterHexKind.ServantMaster, HextechRarityTier.Gold),
		Monster<CuttingEdgeAlchemistRune>(MonsterHexKind.CuttingEdgeAlchemist, HextechRarityTier.Gold),
		Monster<DivineInterventionRune>(MonsterHexKind.DivineIntervention, HextechRarityTier.Gold),
		Monster<SonataRune>(MonsterHexKind.Sonata, HextechRarityTier.Gold),
		Monster<DevilsDanceRune>(MonsterHexKind.DevilsDance, HextechRarityTier.Gold),
		Monster<ImmortalBoneRune>(MonsterHexKind.ImmortalBone, HextechRarityTier.Gold),
		Monster<DoomsdayRune>(MonsterHexKind.Doomsday, HextechRarityTier.Gold),
		Monster<WarmogsSpiritRune>(MonsterHexKind.WarmogsSpirit, HextechRarityTier.Gold),
		Monster<BloodArmorRune>(MonsterHexKind.BloodArmor, HextechRarityTier.Gold),
		Monster<JinlianBoxRune>(MonsterHexKind.JinlianBox, HextechRarityTier.Gold),
		Monster<MirrorReflectionRune>(MonsterHexKind.MirrorReflection, HextechRarityTier.Gold),
		Monster<BlueCandleMedkitRune>(MonsterHexKind.BlueCandleMedkit, HextechRarityTier.Gold),
		Monster<TanksShieldRune>(MonsterHexKind.TanksShield, HextechRarityTier.Gold),
		Monster<ScaredStiffRune>(MonsterHexKind.ScaredStiff, HextechRarityTier.Gold),
		Monster<AncientWineRune>(MonsterHexKind.AncientWine, HextechRarityTier.Gold),
		Monster<PorcupineRune>(MonsterHexKind.Porcupine, HextechRarityTier.Gold),
		Monster<MonarchsGazeRune>(MonsterHexKind.MonarchsGaze, HextechRarityTier.Gold),
		Monster<OmegaRune>(MonsterHexKind.Omega, HextechRarityTier.Gold),
		Monster<ManipulateRealityRune>(MonsterHexKind.ManipulateReality, HextechRarityTier.Gold),
		Monster<NatureIsHealingRune>(MonsterHexKind.NatureIsHealing, HextechRarityTier.Gold),
		Monster<ArchmageRune>(MonsterHexKind.Archmage, HextechRarityTier.Gold),

		Monster<CourageOfColossusRune>(MonsterHexKind.CourageOfColossus, HextechRarityTier.Prismatic),
		Monster<GlassCannonRune>(MonsterHexKind.GlassCannon, HextechRarityTier.Prismatic),
		Monster<GoliathRune>(MonsterHexKind.Goliath, HextechRarityTier.Prismatic),
		Monster<QueenRune>(MonsterHexKind.Queen, HextechRarityTier.Prismatic),
		Monster<HandOfBaronRune>(MonsterHexKind.HandOfBaron, HextechRarityTier.Prismatic),
		Monster<CantTouchThisRune>(MonsterHexKind.CantTouchThis, HextechRarityTier.Prismatic),
		Monster<MasterOfDualityRune>(MonsterHexKind.MasterOfDuality, HextechRarityTier.Prismatic),
		Monster<GoldrendRune>(MonsterHexKind.Goldrend, HextechRarityTier.Prismatic),
		Monster<FeelTheBurnRune>(MonsterHexKind.FeelTheBurn, HextechRarityTier.Prismatic, disabled: true, hasBurnHoverTip: true),
		Monster<BackToBasicsRune>(MonsterHexKind.BackToBasics, HextechRarityTier.Prismatic),
		Monster<MadScientistRune>(MonsterHexKind.MadScientist, HextechRarityTier.Prismatic),
		Monster<FeyMagicRune>(MonsterHexKind.FeyMagic, HextechRarityTier.Prismatic),
		Monster<FinalFormRune>(MonsterHexKind.FinalForm, HextechRarityTier.Prismatic),
		Monster<UnmovableMountainRune>(MonsterHexKind.UnmovableMountain, HextechRarityTier.Prismatic),
		Monster<MikaelsBlessingRune>(MonsterHexKind.MikaelsBlessing, HextechRarityTier.Prismatic),
		Monster<ClownCollegeRune>(MonsterHexKind.ClownCollege, HextechRarityTier.Prismatic),
		Monster<SingularityAIRune>(MonsterHexKind.SingularityAI, HextechRarityTier.Prismatic),
		Monster<ProteinShakeRune>(MonsterHexKind.ProteinShake, HextechRarityTier.Prismatic),
		Monster<GoldenSpatulaRune>(MonsterHexKind.GoldenSpatula, HextechRarityTier.Prismatic),
		Monster<HailToTheKingRune>(MonsterHexKind.HailToTheKing, HextechRarityTier.Prismatic),
		Monster<EightPennyGateRune>(MonsterHexKind.EightPennyGate, HextechRarityTier.Prismatic),
		Monster<DuffsVintageRune>(MonsterHexKind.DuffsVintage, HextechRarityTier.Prismatic),
		Monster<HastyScribbleRune>(MonsterHexKind.HastyScribble, HextechRarityTier.Prismatic),
		Monster<MiseryRune>(MonsterHexKind.Misery, HextechRarityTier.Prismatic),
		Monster<ShoulderVakuRune>(MonsterHexKind.ShoulderVaku, HextechRarityTier.Prismatic),
		Monster<UpgradeRune>(MonsterHexKind.Upgrade, HextechRarityTier.Prismatic),
		Monster<NearDeathFeastRune>(MonsterHexKind.NearDeathFeast, HextechRarityTier.Prismatic),
		Monster<GhostFormRune>(MonsterHexKind.GhostForm, HextechRarityTier.Prismatic),
		Monster<SerpentsFangRune>(MonsterHexKind.SerpentsFang, HextechRarityTier.Prismatic),
		Monster<PandorasBoxRune>(MonsterHexKind.PandorasBox, HextechRarityTier.Prismatic),
		Monster<ForbiddenGrimoireRune>(MonsterHexKind.ForbiddenGrimoire, HextechRarityTier.Prismatic),
		Monster<TezcatarasMercyRune>(MonsterHexKind.TezcatarasMercy, HextechRarityTier.Prismatic),
		Monster<ArcanePunchRune>(MonsterHexKind.ArcanePunch, HextechRarityTier.Prismatic),
		Monster<SymphonyOfWarRune>(MonsterHexKind.SymphonyOfWar, HextechRarityTier.Prismatic),
		Monster<MysteryRune>(MonsterHexKind.Mystery, HextechRarityTier.Prismatic),
		Monster<MindOverMatterRune>(MonsterHexKind.MindOverMatter, HextechRarityTier.Prismatic),
		Monster<CompensationRune>(MonsterHexKind.Compensation, HextechRarityTier.Prismatic),
		Monster<OminousPactRune>(MonsterHexKind.OminousPact, HextechRarityTier.Prismatic),
		Monster<SolidTimeRune>(MonsterHexKind.SolidTime, HextechRarityTier.Prismatic),
		Monster<ForgottenSoulRune>(MonsterHexKind.ForgottenSoul, HextechRarityTier.Prismatic),
		Monster<CerberusRune>(MonsterHexKind.Cerberus, HextechRarityTier.Prismatic),
		Monster<OmniDragonSoulRune>(MonsterHexKind.OmniDragonSoul, HextechRarityTier.Prismatic),
		Monster<BlankCheckRune>(MonsterHexKind.BlankCheck, HextechRarityTier.Prismatic),

		Monster<CorrosionRune>(MonsterHexKind.Corrosion, HextechRarityTier.Silver),
		Monster<BrutalityRune>(MonsterHexKind.Brutality, HextechRarityTier.Silver),
		Monster<JudicatorRune>(MonsterHexKind.Judicator, HextechRarityTier.Gold),
		Monster<SoulEaterRune>(MonsterHexKind.SoulEater, HextechRarityTier.Gold),
		Monster<DeathHarvestRune>(MonsterHexKind.DeathHarvest, HextechRarityTier.Gold),
		Monster<GiantSlayerRune>(MonsterHexKind.GiantSlayer, HextechRarityTier.Prismatic),
		Monster<DualWieldRune>(MonsterHexKind.DualWield, HextechRarityTier.Prismatic)
	];

	private static MonsterHexRegistration Monster<TRelic>(
		MonsterHexKind kind,
		HextechRarityTier rarity,
		bool disabled = false,
		bool hasBurnHoverTip = false)
	{
		return new MonsterHexRegistration(kind, rarity, typeof(TRelic), disabled, hasBurnHoverTip);
	}
}
